# Generated by Django 4.2.4 on 2023-09-13 04:08

from django.db import migrations, models
import functools
import import_export_extensions.models.tools


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_extensions', '0003_importjob_skip_parse_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='input_errors_file',
            field=models.FileField(help_text='File that contain failed rows', max_length=512, null=True, upload_to=functools.partial(import_export_extensions.models.tools.upload_file_to, *(), **{'main_folder_name': 'import'}), verbose_name='Input errors file'),
        ),
    ]
