# Generated by Django 4.2.7 on 2024-01-15 10:40

import functools

from django.db import migrations, models

import import_export_extensions.models.tools


class Migration(migrations.Migration):
    dependencies = [
        ("import_export_extensions", "0005_importjob_force_import"),
    ]

    operations = [
        migrations.AddField(
            model_name="importjob",
            name="input_errors_file",
            field=models.FileField(
                help_text="File that contain failed rows",
                max_length=512,
                null=True,
                upload_to=functools.partial(
                    import_export_extensions.models.tools.upload_file_to,
                    *(),
                    main_folder_name="import",
                ),
                verbose_name="Input errors file",
            ),
        ),
    ]
