# Generated by Django 5.1.6 on 2025-03-20 11:59

import functools

from django.db import migrations, models

import import_export_extensions.models.tools


class Migration(migrations.Migration):
    dependencies = [
        (
            "import_export_extensions",
            "0008_alter_exportjob_id_alter_importjob_id",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportjob",
            name="data_file",
            field=models.FileField(
                help_text="File that contain exported data",
                max_length=512,
                storage=import_export_extensions.models.tools.select_storage,
                upload_to=functools.partial(
                    import_export_extensions.models.tools.upload_file_to,
                    *(),
                    main_folder_name="export",
                ),
                verbose_name="Data file",
            ),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="data_file",
            field=models.FileField(
                help_text="File that contain data to be imported",
                max_length=512,
                storage=import_export_extensions.models.tools.select_storage,
                upload_to=functools.partial(
                    import_export_extensions.models.tools.upload_file_to,
                    *(),
                    main_folder_name="import",
                ),
                verbose_name="Data file",
            ),
        ),
    ]
