# Generated by Django 6.0.2 on 2026-03-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_extensions', '0009_alter_exportjob_data_file_alter_importjob_data_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportjob',
            name='export_task_id',
            field=models.CharField(blank=True, help_text='Task ID that start `export_data`', max_length=36, null=True, verbose_name='Export task ID'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='import_task_id',
            field=models.CharField(default=str, help_text='Task ID that start `import_data`', max_length=36, verbose_name='Import task ID'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='parse_task_id',
            field=models.CharField(default=str, help_text='Task ID that start `parse_data`', max_length=36, verbose_name='Parsing task ID'),
        ),
    ]
