# Generated by Django 6.1 on 2026-10-02 02:52

import functools

from django.db import migrations, models

import import_export_extensions.models.tools


class Migration(migrations.Migration):
    dependencies = [
        (
            "import_export_extensions",
            "0009_alter_exportjob_data_file_alter_importjob_data_file",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportjob",
            name="data_file",
            field=models.FileField(
                help_text="File that contain exported data",
                max_length=512,
                null=True,
                storage=import_export_extensions.models.tools.select_storage,
                upload_to=functools.partial(
                    import_export_extensions.models.tools.upload_file_to,
                    main_folder_name="export",
                ),
                verbose_name="Data file",
            ),
        ),
    ]
