default_stages: [
  pre-commit,
  pre-push,
]
default_install_hook_types: [
  pre-commit,
  pre-push,
  post-checkout,
  post-merge,
  post-rewrite,
]
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-xml
      - id: check-json
        exclude: ".*\\.vscode/"
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-aws-credentials
        args: [
          --allow-missing-credentials,
        ]
      - id: debug-statements
      - id: check-merge-conflict
        args: [
          --assume-in-merge,
        ]
      - id: detect-private-key
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: check-added-large-files
        args: [
          --maxkb=1000,
        ]
      - id: file-contents-sorter
        files: "\\.vscode/(boilerplate-words|project-related-words)\\.txt"
        args: [
          --ignore-case,
        ]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.1
    hooks:
      - id: gitleaks

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.10
    hooks:
      - id: ruff-check
        args: [
          --fix,
        ]
      - id: ruff-format

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v10.0.0
    hooks:
      - id: cspell

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v4.0.0
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.6
    hooks:
      - id: uv-lock
      - id: uv-sync
        args: [
          --all-groups
        ]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.48.0
    hooks:
      - id: markdownlint
        args: [
          "--fix",
        ]

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.12
    hooks:
      - id: actionlint

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
      - id: yamllint

  - repo: local
    hooks:
      - id: mypy
        name: Run mypy
        entry: inv mypy.run
        language: system
        pass_filenames: false
        types: [ file ]
        stages: [ pre-push ]
      - id: doc-build-verify
        name: Verify that docs could be build
        entry: inv docs.build
        language: system
        pass_filenames: false
        types: [ file ]
        stages: [ pre-push ]
      - id: tests
        name: run tests
        entry: inv pytest.run --params="--numprocesses auto --create-db --cov=."
        language: system
        pass_filenames: false
        types: [ python ]
        stages: [ pre-push ]
