services:
  redis:
    image: redis:latest@sha256:1f073813b641755b70b0200da64131bbeeb4ec5b633ca67772229b49820caafa
    ports:
      - "6379:6379"
  postgres:
    image: postgres:latest@sha256:52e6ffd11fddd081ae63880b635b2a61c14008c17fc98cdc7ce5472265516dd0
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h postgres -t 5 -U ${COMPOSE_PROJECT_NAME}-user || false" ]
      interval: 1s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_DB=${COMPOSE_PROJECT_NAME}-dev
      - POSTGRES_USER=${COMPOSE_PROJECT_NAME}-user
      - POSTGRES_PASSWORD=testpass
