# Generated by Django 4.2.7 on 2024-05-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fake_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
