# Generated by Django 5.1.1 on 2024-10-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fake_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="bands",
            field=models.ManyToManyField(
                related_name="artists",
                through="fake_app.Membership",
                to="fake_app.band",
            ),
        ),
    ]
