# Generated by Django 5.1.1 on 2024-10-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fake_app", "0002_alter_artist_bands"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="external_id",
            field=models.CharField(
                editable=False,
                help_text="External ID for sync import objects.",
                null=True,
                unique=True,
                verbose_name="External ID",
            ),
        ),
    ]
