name: Publish to PyPI

on:
  release:
    types: [
      published,
    ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # Fallback to plain text output for reducing docker output
  # https://github.com/docker/compose/issues/8753#issuecomment-934473781
  BUILDKIT_PROGRESS: plain
  # Disable PTY for Invoke to avoid issues in CI environments and reduce output
  INVOKE_PTY: false

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write  # For Trusted Publishing
      contents: write
    steps:
      - name: Run
        uses: saritasa-nest/saritasa-python-open-source-boilerplate/.github/actions/publish@main
      - name: Report failure
        if: failure() && github.event_name == 'release'
        uses: saritasa-nest/saritasa-python-open-source-boilerplate/.github/actions/report_action_failure@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
